-- MySQL Script generated by MySQL Workbench
-- Thu Apr  2 19:55:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema home_design_solutions`
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `home_design_solutions`;

-- -----------------------------------------------------
-- Schema home_design_solutions`
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `home_design_solutions`;
-- -----------------------------------------------------
-- Schema home_design_solutions
-- -----------------------------------------------------
USE `home_design_solutions`;

-- -----------------------------------------------------
-- Table `home_design_solutions`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_design_solutions`.`Customer`;

CREATE TABLE IF NOT EXISTS `home_design_solutions`.`Customer`
(
    `address`       VARCHAR(191) NOT NULL,
    `city`          VARCHAR(191) NOT NULL,
    `createdAt`     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `firstName`     VARCHAR(191) NOT NULL,
    `idCustomer`    INT          NOT NULL AUTO_INCREMENT,
    `lastName`      VARCHAR(191) NOT NULL,
    `middleInitial` VARCHAR(191) NULL     DEFAULT NULL,
    `state`         VARCHAR(191) NOT NULL,
    `updatedAt`     DATETIME(3)  NOT NULL,
    `zipCode`       INT          NOT NULL,
    PRIMARY KEY (`idCustomer`)
)
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `home_design_solutions`.`CustomerOrder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_design_solutions`.`CustomerOrder`;

CREATE TABLE IF NOT EXISTS `home_design_solutions`.`CustomerOrder`
(
    `actualDeliveryDate`   DATETIME(3)     NULL     DEFAULT NULL,
    `customerId`           INT             NOT NULL,
    `dateCancelled`        DATETIME(3)     NULL     DEFAULT NULL,
    `expectedDeliveryDate` DATETIME(3)     NOT NULL,
    `idCustomerOrder`      INT             NOT NULL AUTO_INCREMENT,
    `isCanceled`           INT             NULL     DEFAULT 0,
    `orderDate`            DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `orderNumber`          INT             NOT NULL,
    `orderTotal`           DECIMAL(65, 30) NOT NULL,
    `storeLocationId`      INT             NOT NULL,
    PRIMARY KEY (`idCustomerOrder`),
    CONSTRAINT `customerorder_ibfk_1`
        FOREIGN KEY (`customerId`)
            REFERENCES `home_design_solutions`.`Customer` (`idCustomer`)
            ON DELETE cascade
            ON UPDATE cascade,
    CONSTRAINT `customerorder_ibfk_2`
        FOREIGN KEY (`storeLocationId`)
            REFERENCES `home_design_solutions`.`StoreLocations` (`idStoreLocations`)
            ON DELETE cascade
            ON UPDATE cascade
)
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `CustomerOrder.orderNumber` ON `home_design_solutions`.`CustomerOrder` (`orderNumber` ASC) VISIBLE;

CREATE INDEX `customerId_idx` ON `home_design_solutions`.`CustomerOrder` (`customerId` ASC) VISIBLE;

CREATE INDEX `storeLocationId_idx` ON `home_design_solutions`.`CustomerOrder` (`storeLocationId` ASC) VISIBLE;

CREATE INDEX `customerorder_ibfk_1` ON `home_design_solutions`.`CustomerOrder` (`customerId` ASC) VISIBLE;

CREATE INDEX `customerorder_ibfk_2` ON `home_design_solutions`.`CustomerOrder` (`storeLocationId` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `home_design_solutions`.`CustomerOrderProducts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_design_solutions`.`CustomerOrderProducts`;

CREATE TABLE IF NOT EXISTS `home_design_solutions`.`CustomerOrderProducts`
(
    `customerOrderId`         INT             NOT NULL,
    `idCustomerOrderProducts` INT             NOT NULL AUTO_INCREMENT,
    `perUnitCost`             DECIMAL(65, 30) NOT NULL,
    `productId`               INT             NOT NULL,
    `quantity`                INT             NOT NULL,
    PRIMARY KEY (`idCustomerOrderProducts`),
    CONSTRAINT `customerorderproducts_ibfk_1`
        FOREIGN KEY (`customerOrderId`)
            REFERENCES `home_design_solutions`.`CustomerOrder` (`idCustomerOrder`)
            ON DELETE cascade
            ON UPDATE cascade,
    CONSTRAINT `customerorderproducts_ibfk_2`
        FOREIGN KEY (`productId`)
            REFERENCES `home_design_solutions`.`Product` (`idProduct`)
            ON DELETE cascade
            ON UPDATE cascade
)
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `customerOrderId_idx` ON `home_design_solutions`.`CustomerOrderProducts` (`customerOrderId` ASC) VISIBLE;

CREATE INDEX `productId_idx` ON `home_design_solutions`.`CustomerOrderProducts` (`productId` ASC) VISIBLE;

CREATE INDEX `customerorderproducts_ibfk_1` ON `home_design_solutions`.`CustomerOrderProducts` (`customerOrderId` ASC) VISIBLE;

CREATE INDEX `customerorderproducts_ibfk_2` ON `home_design_solutions`.`CustomerOrderProducts` (`productId` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `home_design_solutions`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_design_solutions`.`Employee`;

CREATE TABLE IF NOT EXISTS `home_design_solutions`.`Employee`
(
    `address`           VARCHAR(191)                                                                                                                                                                                                                                                                                                            NOT NULL,
    `city`              VARCHAR(191)                                                                                                                                                                                                                                                                                                            NOT NULL,
    `createdAt`         DATETIME                                                                                                                                                                                                                                                                                                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `email`             VARCHAR(191)                                                                                                                                                                                                                                                                                                            NOT NULL,
    `employeeId`        INT                                                                                                                                                                                                                                                                                                                     NOT NULL AUTO_INCREMENT,
    `firstName`         VARCHAR(191)                                                                                                                                                                                                                                                                                                            NOT NULL,
    `lastName`          VARCHAR(191)                                                                                                                                                                                                                                                                                                            NOT NULL,
    `password`          VARCHAR(191)                                                                                                                                                                                                                                                                                                            NOT NULL,
    `positionName`      ENUM ('PRESIDENT_CEO', 'VP_CEO', 'STORE_MANAGER', 'OFFICE_MANAGER', 'SALES_DESIGN_MANAGER', 'SALES_DESIGN_ASSOCIATE', 'SCHEDULING', 'TECHNICIAN', 'DELIVERY', 'WAREHOUSE', 'INSTALLATIONS', 'INSTALLATIONS_DELIVERIES', 'INSTALLATIONS_DELIVERIES_SALES', 'WAREHOUSE_INSTALLATIONS_DELIVERIES', 'WAREHOUSE_DELIVERIES') NOT NULL,
    `roleCapability`    ENUM ('READ_WRITE', 'READ', 'NONE')                                                                                                                                                                                                                                                                                     NOT NULL DEFAULT 'NONE',
    `salary`            DECIMAL(65, 30)                                                                                                                                                                                                                                                                                                         NOT NULL,
    `state`             VARCHAR(191)                                                                                                                                                                                                                                                                                                            NOT NULL,
    `storeLocationId`   INT                                                                                                                                                                                                                                                                                                                     NOT NULL,
    `updatedAt`         DATETIME(3)                                                                                                                                                                                                                                                                                                             NOT NULL,
    `userSigningSecret` VARCHAR(191)                                                                                                                                                                                                                                                                                                            NOT NULL,
    `zipCode`           INT                                                                                                                                                                                                                                                                                                                     NOT NULL,
    PRIMARY KEY (`employeeId`),
    CONSTRAINT `employee_ibfk_1`
        FOREIGN KEY (`storeLocationId`)
            REFERENCES `home_design_solutions`.`StoreLocations` (`idStoreLocations`)
            ON DELETE cascade
            ON UPDATE cascade
)
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `Employee.email` ON `home_design_solutions`.`Employee` (`email` ASC) VISIBLE;

CREATE INDEX `storeLocationId_idx` ON `home_design_solutions`.`Employee` (`storeLocationId` ASC) VISIBLE;

CREATE INDEX `employee_ibfk_1` ON `home_design_solutions`.`Employee` (`storeLocationId` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `home_design_solutions`.`Inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_design_solutions`.`Inventory`;

CREATE TABLE IF NOT EXISTS `home_design_solutions`.`Inventory`
(
    `aisle`          INT          NOT NULL,
    `bin`            VARCHAR(191) NOT NULL,
    `idInventory`    INT          NOT NULL AUTO_INCREMENT,
    `product`        INT          NOT NULL,
    `quantityOnHand` INT          NOT NULL,
    `storeLocation`  INT          NOT NULL,
    PRIMARY KEY (`idInventory`),
    CONSTRAINT `inventory_ibfk_1`
        FOREIGN KEY (`product`)
            REFERENCES `home_design_solutions`.`Product` (`idProduct`)
            ON DELETE cascade
            ON UPDATE cascade,
    CONSTRAINT `inventory_ibfk_2`
        FOREIGN KEY (`storeLocation`)
            REFERENCES `home_design_solutions`.`StoreLocations` (`idStoreLocations`)
            ON DELETE cascade
            ON UPDATE cascade
)
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `Inventory.bin` ON `home_design_solutions`.`Inventory` (`bin` ASC) VISIBLE;

CREATE INDEX `productId_idx` ON `home_design_solutions`.`Inventory` (`product` ASC) VISIBLE;

CREATE INDEX `storeLocationId_idx` ON `home_design_solutions`.`Inventory` (`storeLocation` ASC) VISIBLE;

CREATE INDEX `inventory_ibfk_1` ON `home_design_solutions`.`Inventory` (`product` ASC) VISIBLE;

CREATE INDEX `inventory_ibfk_2` ON `home_design_solutions`.`Inventory` (`storeLocation` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `home_design_solutions`.`Invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_design_solutions`.`Invoice`;

CREATE TABLE IF NOT EXISTS `home_design_solutions`.`Invoice`
(
    `createdAt`       DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `customerId`      INT             NOT NULL,
    `customerOrderId` INT             NOT NULL,
    `dueDate`         DATETIME(3)     NOT NULL,
    `employeeId`      INT             NOT NULL,
    `idInvoice`       INT             NOT NULL AUTO_INCREMENT,
    `invoiceNumber`   VARCHAR(191)    NOT NULL,
    `invoiceTotal`    DECIMAL(65, 30) NOT NULL,
    `paidDate`        DATETIME(3)     NOT NULL,
    `storeLocationId` INT             NOT NULL,
    `updatedAt`       DATETIME(3)     NOT NULL,
    `job`             INT             NOT NULL,
    PRIMARY KEY (`idInvoice`),
    CONSTRAINT `invoice_ibfk_1`
        FOREIGN KEY (`customerId`)
            REFERENCES `home_design_solutions`.`Customer` (`idCustomer`)
            ON DELETE cascade
            ON UPDATE cascade,
    CONSTRAINT `invoice_ibfk_2`
        FOREIGN KEY (`customerOrderId`)
            REFERENCES `home_design_solutions`.`CustomerOrder` (`idCustomerOrder`)
            ON DELETE cascade
            ON UPDATE cascade,
    CONSTRAINT `invoice_ibfk_3`
        FOREIGN KEY (`employeeId`)
            REFERENCES `home_design_solutions`.`Employee` (`employeeId`)
            ON DELETE cascade
            ON UPDATE cascade,
    CONSTRAINT `invoice_ibfk_4`
        FOREIGN KEY (`storeLocationId`)
            REFERENCES `home_design_solutions`.`StoreLocations` (`idStoreLocations`)
            ON DELETE cascade
            ON UPDATE cascade,
    CONSTRAINT `invoice_ibfk_5`
        FOREIGN KEY (`job`)
            REFERENCES `home_design_solutions`.`Jobs` (`idJobs`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `Invoice.invoiceNumber` ON `home_design_solutions`.`Invoice` (`invoiceNumber` ASC) VISIBLE;

CREATE INDEX `customerId_idx` ON `home_design_solutions`.`Invoice` (`customerId` ASC) VISIBLE;

CREATE INDEX `customerOrderId_idx` ON `home_design_solutions`.`Invoice` (`customerOrderId` ASC) VISIBLE;

CREATE INDEX `employeeId_idx` ON `home_design_solutions`.`Invoice` (`employeeId` ASC) VISIBLE;

CREATE INDEX `storeLocationId_idx` ON `home_design_solutions`.`Invoice` (`storeLocationId` ASC) VISIBLE;

CREATE INDEX `invoice_ibfk_1` ON `home_design_solutions`.`Invoice` (`customerId` ASC) VISIBLE;

CREATE INDEX `invoice_ibfk_2` ON `home_design_solutions`.`Invoice` (`customerOrderId` ASC) VISIBLE;

CREATE INDEX `invoice_ibfk_3` ON `home_design_solutions`.`Invoice` (`employeeId` ASC) VISIBLE;

CREATE INDEX `invoice_ibfk_4` ON `home_design_solutions`.`Invoice` (`storeLocationId` ASC) VISIBLE;

CREATE INDEX `invoice_ibfk_5_idx` ON `home_design_solutions`.`Invoice` (`job` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `home_design_solutions`.`InvoiceLineItems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_design_solutions`.`InvoiceLineItems`;

CREATE TABLE IF NOT EXISTS `home_design_solutions`.`InvoiceLineItems`
(
    `idinvoiceLineItem` INT             NOT NULL AUTO_INCREMENT,
    `invoiceId`         INT             NOT NULL,
    `lineItemTotal`     DECIMAL(65, 30) NOT NULL,
    `productId`         INT             NULL DEFAULT NULL,
    `quantity`          INT             NOT NULL,
    PRIMARY KEY (`idinvoiceLineItem`),
    CONSTRAINT `invoicelineitems_ibfk_1`
        FOREIGN KEY (`invoiceId`)
            REFERENCES `home_design_solutions`.`Invoice` (`idInvoice`)
            ON DELETE cascade
            ON UPDATE cascade,
    CONSTRAINT `invoicelineitems_ibfk_4`
        FOREIGN KEY (`productId`)
            REFERENCES `home_design_solutions`.`Product` (`idProduct`)
            ON DELETE set null
            ON UPDATE cascade
)
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `invoiceId_idx` ON `home_design_solutions`.`InvoiceLineItems` (`invoiceId` ASC) VISIBLE;

CREATE INDEX `productId_idx` ON `home_design_solutions`.`InvoiceLineItems` (`productId` ASC) VISIBLE;

CREATE INDEX `invoicelineitems_ibfk_1` ON `home_design_solutions`.`InvoiceLineItems` (`invoiceId` ASC) VISIBLE;

CREATE INDEX `invoicelineitems_ibfk_4` ON `home_design_solutions`.`InvoiceLineItems` (`productId` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `home_design_solutions`.`Jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_design_solutions`.`Jobs`;

CREATE TABLE IF NOT EXISTS `home_design_solutions`.`Jobs`
(
    `customerId`     INT             NOT NULL,
    `dateCompleted`  DATETIME(3)     NOT NULL,
    `dateScheduled`  DATETIME(3)     NOT NULL,
    `details`        VARCHAR(191)    NULL DEFAULT NULL,
    `hoursActual`    DECIMAL(65, 30) NULL DEFAULT NULL,
    `hoursScheduled` DECIMAL(65, 30) NOT NULL,
    `idJobs`         INT             NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`idJobs`),
    CONSTRAINT `jobs_ibfk_1`
        FOREIGN KEY (`customerId`)
            REFERENCES `home_design_solutions`.`Customer` (`idCustomer`)
            ON DELETE cascade
            ON UPDATE cascade
)
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `customerId_idx` ON `home_design_solutions`.`Jobs` (`customerId` ASC) VISIBLE;

CREATE INDEX `jobs_ibfk_1` ON `home_design_solutions`.`Jobs` (`customerId` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `home_design_solutions`.`MagicCode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_design_solutions`.`MagicCode`;

CREATE TABLE IF NOT EXISTS `home_design_solutions`.`MagicCode`
(
    `code`      VARCHAR(191) NOT NULL,
    `updatedAt` DATETIME(3)  NOT NULL,
    `userId`    INT          NOT NULL,
    PRIMARY KEY (`code`),
    CONSTRAINT `magiccode_ibfk_1`
        FOREIGN KEY (`userId`)
            REFERENCES `home_design_solutions`.`Employee` (`employeeId`)
            ON DELETE cascade
            ON UPDATE cascade
)
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `MagicCode_userId` ON `home_design_solutions`.`MagicCode` (`userId` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `home_design_solutions`.`_Migration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_design_solutions`.`_Migration`;

CREATE TABLE IF NOT EXISTS `home_design_solutions`.`_Migration`
(
    `revision`           INT         NOT NULL AUTO_INCREMENT,
    `name`               TEXT        NOT NULL,
    `datamodel`          LONGTEXT    NOT NULL,
    `status`             TEXT        NOT NULL,
    `applied`            INT         NOT NULL,
    `rolled_back`        INT         NOT NULL,
    `datamodel_steps`    LONGTEXT    NOT NULL,
    `database_migration` LONGTEXT    NOT NULL,
    `errors`             LONGTEXT    NOT NULL,
    `started_at`         DATETIME(3) NOT NULL,
    `finished_at`        DATETIME(3) NULL DEFAULT NULL,
    PRIMARY KEY (`revision`)
);


-- -----------------------------------------------------
-- Table `home_design_solutions`.`Operations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_design_solutions`.`Operations`;

CREATE TABLE IF NOT EXISTS `home_design_solutions`.`Operations`
(
    `chargePerHour` DECIMAL(65, 30) NOT NULL,
    `hoursCharged`  DECIMAL(65, 30) NOT NULL,
    `idOperations`  INT             NOT NULL AUTO_INCREMENT,
    `jobId`         INT             NOT NULL,
    `operationName` VARCHAR(191)    NOT NULL,
    `details`       VARCHAR(191)    NULL,
    PRIMARY KEY (`idOperations`),
    CONSTRAINT `operations_ibfk_1`
        FOREIGN KEY (`jobId`)
            REFERENCES `home_design_solutions`.`Jobs` (`idJobs`)
            ON DELETE cascade
            ON UPDATE cascade
)
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `jobId_idx` ON `home_design_solutions`.`Operations` (`jobId` ASC) VISIBLE;

CREATE INDEX `operations_ibfk_1` ON `home_design_solutions`.`Operations` (`jobId` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `home_design_solutions`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_design_solutions`.`Product`;

CREATE TABLE IF NOT EXISTS `home_design_solutions`.`Product`
(
    `brand`           VARCHAR(191)    NOT NULL,
    `createdAt`       DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deliveryPrice`   DECIMAL(65, 30) NOT NULL,
    `description`     VARCHAR(191)    NULL     DEFAULT NULL,
    `idProduct`       INT             NOT NULL AUTO_INCREMENT,
    `listPrice`       DECIMAL(65, 30) NOT NULL,
    `modelNumber`     VARCHAR(191)    NOT NULL,
    `productCategory` VARCHAR(191)    NOT NULL,
    `salePrice`       DECIMAL(65, 30) NULL     DEFAULT NULL,
    `serialNumber`    VARCHAR(191)    NOT NULL,
    `unitPrice`       DECIMAL(65, 30) NOT NULL,
    `updatedAt`       DATETIME(3)     NOT NULL,
    PRIMARY KEY (`idProduct`)
)
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `Product.serialNumber` ON `home_design_solutions`.`Product` (`serialNumber` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `home_design_solutions`.`SalesOrderItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_design_solutions`.`SalesOrderItem`;

CREATE TABLE IF NOT EXISTS `home_design_solutions`.`SalesOrderItem`
(
    `idSalesOrderItem`  INT             NOT NULL AUTO_INCREMENT,
    `productId`         INT             NOT NULL,
    `quantityPurchased` INT             NOT NULL,
    `salesOrderId`      INT             NOT NULL,
    `unitPrice`         DECIMAL(65, 30) NOT NULL,
    PRIMARY KEY (`idSalesOrderItem`),
    CONSTRAINT `salesorderitem_ibfk_1`
        FOREIGN KEY (`productId`)
            REFERENCES `home_design_solutions`.`Product` (`idProduct`)
            ON DELETE cascade
            ON UPDATE cascade,
    CONSTRAINT `salesorderitem_ibfk_2`
        FOREIGN KEY (`salesOrderId`)
            REFERENCES `home_design_solutions`.`SalesOrders` (`idSalesOrders`)
            ON DELETE cascade
            ON UPDATE cascade
)
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `productId_idx` ON `home_design_solutions`.`SalesOrderItem` (`productId` ASC) VISIBLE;

CREATE INDEX `salesOrderId_idx` ON `home_design_solutions`.`SalesOrderItem` (`salesOrderId` ASC) VISIBLE;

CREATE INDEX `salesorderitem_ibfk_1` ON `home_design_solutions`.`SalesOrderItem` (`productId` ASC) VISIBLE;

CREATE INDEX `salesorderitem_ibfk_2` ON `home_design_solutions`.`SalesOrderItem` (`salesOrderId` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `home_design_solutions`.`SalesOrders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_design_solutions`.`SalesOrders`;

CREATE TABLE IF NOT EXISTS `home_design_solutions`.`SalesOrders`
(
    `deliverDate`     DATETIME(3)     NOT NULL,
    `employeeId`      INT             NOT NULL,
    `idSalesOrders`   INT             NOT NULL AUTO_INCREMENT,
    `orderDate`       DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `orderNumber`     VARCHAR(191)    NOT NULL,
    `orderPrice`      DECIMAL(65, 30) NOT NULL,
    `storeLocationId` INT             NOT NULL,
    `supplierId`      INT             NOT NULL,
    PRIMARY KEY (`idSalesOrders`),
    CONSTRAINT `salesorders_ibfk_1`
        FOREIGN KEY (`employeeId`)
            REFERENCES `home_design_solutions`.`Employee` (`employeeId`)
            ON DELETE cascade
            ON UPDATE cascade,
    CONSTRAINT `salesorders_ibfk_2`
        FOREIGN KEY (`storeLocationId`)
            REFERENCES `home_design_solutions`.`StoreLocations` (`idStoreLocations`)
            ON DELETE cascade
            ON UPDATE cascade,
    CONSTRAINT `salesorders_ibfk_3`
        FOREIGN KEY (`supplierId`)
            REFERENCES `home_design_solutions`.`Suppliers` (`idSupplier`)
            ON DELETE cascade
            ON UPDATE cascade
)
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `SalesOrders.orderNumber` ON `home_design_solutions`.`SalesOrders` (`orderNumber` ASC) VISIBLE;

CREATE INDEX `idStoreLocationIdx` ON `home_design_solutions`.`SalesOrders` (`storeLocationId` ASC) VISIBLE;

CREATE INDEX `idSupplierIdx` ON `home_design_solutions`.`SalesOrders` (`supplierId` ASC) VISIBLE;

CREATE INDEX `id_employeeIdx` ON `home_design_solutions`.`SalesOrders` (`employeeId` ASC) VISIBLE;

CREATE INDEX `salesorders_ibfk_1` ON `home_design_solutions`.`SalesOrders` (`employeeId` ASC) VISIBLE;

CREATE INDEX `salesorders_ibfk_2` ON `home_design_solutions`.`SalesOrders` (`storeLocationId` ASC) VISIBLE;

CREATE INDEX `salesorders_ibfk_3` ON `home_design_solutions`.`SalesOrders` (`supplierId` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `home_design_solutions`.`StoreLocations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_design_solutions`.`StoreLocations`;

CREATE TABLE IF NOT EXISTS `home_design_solutions`.`StoreLocations`
(
    `address`          VARCHAR(191) NOT NULL,
    `city`             VARCHAR(191) NOT NULL,
    `idStoreLocations` INT          NOT NULL AUTO_INCREMENT,
    `phone`            VARCHAR(191) NOT NULL,
    `state`            VARCHAR(191) NOT NULL,
    `zipCode`          INT          NOT NULL,
    PRIMARY KEY (`idStoreLocations`)
)
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `home_design_solutions`.`Suppliers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_design_solutions`.`Suppliers`;

CREATE TABLE IF NOT EXISTS `home_design_solutions`.`Suppliers`
(
    `city`       VARCHAR(191) NOT NULL,
    `createdAt`  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `email`      VARCHAR(191) NOT NULL,
    `idSupplier` INT          NOT NULL AUTO_INCREMENT,
    `name`       VARCHAR(191) NOT NULL,
    `phone`      VARCHAR(191) NOT NULL,
    `state`      VARCHAR(191) NOT NULL,
    `updatedAt`  DATETIME(3)  NOT NULL,
    `zip`        INT          NOT NULL,
    PRIMARY KEY (`idSupplier`)
)
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `Suppliers.email` ON `home_design_solutions`.`Suppliers` (`email` ASC) VISIBLE;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
