import {
  AccountCircle,
  AttachMoneyTwoTone,
  BusinessCenterTwoTone,
  BusinessSharp,
  CallToActionTwoTone,
  DeckTwoTone,
  GpsFixedTwoTone,
  LoyaltyTwoTone,
  MonetizationOnTwoTone,
  MoneySharp,
  ReceiptTwoTone,
} from '@material-ui/icons'

export default Object.freeze([
  {
    pathname: '/dashboard',
    slug: 'dashboard',
    prettyName: 'Dashboard',
    includeInNav: true,
    icon: AccountCircle,
  },
  {
    pathname: '/dashboard/employees',
    slug: 'employees',
    prettyName: 'Employees',
    includeInNav: true,
    icon: BusinessCenterTwoTone,
  },
  {
    pathname: '/dashboard/suppliers',
    slug: 'suppliers',
    prettyName: 'Suppliers',
    includeInNav: true,
    icon: BusinessSharp,
  },
  {
    pathname: '/dashboard/inventories',
    slug: 'inventories',
    prettyName: 'Inventories',
    includeInNav: true,
    icon: LoyaltyTwoTone,
  },
  {
    pathname: '/dashboard/products',
    slug: 'products',
    prettyName: 'Products',
    includeInNav: true,
    icon: DeckTwoTone,
  },
  {
    pathname: '/dashboard/product-order',
    slug: 'product-order',
    prettyName: 'Product Order',
    includeInNav: true,
    icon: ReceiptTwoTone,
  },
  {
    pathname: '/dashboard/locations',
    slug: 'locations',
    prettyName: 'Locations',
    includeInNav: true,
    icon: GpsFixedTwoTone,
  },
  {
    pathname: '/dashboard/jobs',
    slug: 'jobs',
    prettyName: 'Jobs',
    includeInNav: true,
    icon: CallToActionTwoTone,
  },
  {
    pathname: '/dashboard/bids',
    slug: 'bids',
    prettyName: 'Bids',
    includeInNav: true,
    icon: AttachMoneyTwoTone,
  },
  {
    pathname: '/dashboard/customer-sales',
    slug: '/customer-sales',
    prettyName: 'Customer Sales',
    includeInNav: true,
    icon: MoneySharp,
  },
  {
    pathname: '/dashboard/customer-orders',
    slug: '/customer-orders',
    prettyName: 'Customer Orders',
    includeInNav: true,
    icon: MonetizationOnTwoTone,
  },
])
