import {
  AccountCircle,
  BusinessCenterTwoTone,
  BusinessSharp,
  CallToActionTwoTone,
  DeckTwoTone,
  GpsFixedTwoTone,
  LoyaltyTwoTone,
  MonetizationOnTwoTone,
  MoneySharp,
  PersonOutlineOutlined,
  ReceiptTwoTone,
} from '@material-ui/icons'

export default Object.freeze([
  {
    pathname: '/dashboard',
    slug: 'dashboard',
    prettyName: 'Dashboard',
    includeInNav: true,
    icon: AccountCircle,
  },
  {
    pathname: '/dashboard/employees',
    slug: 'employees',
    prettyName: 'Employees',
    includeInNav: true,
    icon: BusinessCenterTwoTone,
  },
  {
    pathname: '/dashboard/suppliers',
    slug: 'suppliers',
    prettyName: 'Suppliers',
    includeInNav: true,
    icon: BusinessSharp,
  },
  {
    pathname: '/dashboard/locations',
    slug: 'locations',
    prettyName: 'Locations',
    includeInNav: true,
    icon: GpsFixedTwoTone,
  },
  {
    pathname: '/dashboard/inventories',
    slug: 'inventories',
    prettyName: 'Inventories',
    includeInNav: true,
    icon: LoyaltyTwoTone,
  },
  {
    pathname: '/dashboard/products',
    slug: 'products',
    prettyName: 'Products',
    includeInNav: true,
    icon: DeckTwoTone,
  },
  {
    pathname: '/dashboard/customers',
    slug: 'customers',
    prettyName: 'Customers',
    includeInNav: true,
    icon: PersonOutlineOutlined,
  },
  {
    pathname: '/dashboard/sales-order',
    slug: 'sales-order',
    prettyName: 'Sales Order',
    includeInNav: true,
    icon: ReceiptTwoTone,
  },
  {
    pathname: '/dashboard/customer-sales',
    slug: 'customer-sales',
    prettyName: 'Customer Sales',
    includeInNav: true,
    icon: MoneySharp,
  },
  {
    pathname: '/dashboard/point-of-sale',
    slug: 'customer-orders',
    prettyName: 'Point of Sale',
    includeInNav: true,
    icon: MonetizationOnTwoTone,
  },
  {
    pathname: '/dashboard/jobs',
    slug: 'jobs',
    prettyName: 'Jobs',
    includeInNav: true,
    icon: CallToActionTwoTone,
  },
])
